services:
  db:
    image: postgres:15
    container_name: etl_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  etl_app:
    build: .
    container_name: etl_app
    env_file: .env
    depends_on:
      - db
    command: python main.py

volumes:
  db_data:
